Add project People
vue-a11y/vue-a11y.com pull request #53
Opened 2021-02-01 18:50 UTC by ktquez

2021-02-01 19:42 UTC, marcus-herrmann requested changes

2021-02-01 19:42 UTC, marcus-herrmann commented on src/project/people.md
Typo: maintainers

2021-02-01 19:45 UTC, ktquez commented on src/project/people.md
Thanks @marcus-herrmann 
Done!

2021-02-01 23:40 UTC, yamanoku commented on src/.vuepress/config/people.js
> +    bio: 'FrontEnd Designer • Accessibility Adovocator • I want to be Internet.'
```suggestion
    bio: 'FrontEnd Designer • Accessibility Adovocator'
```
This is it, please.

2021-02-02 09:14 UTC, yamanoku approved these changes
thanks ❤️

2021-02-02 09:18 UTC, merged